spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://172.21.41.92:8000/stc_qzj
    username: mj_jc
    password: "mj_jc@0127!"
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 30000

dhis2:
  base-url: http://59.225.208.148:8015
  username: admin
  password: district
  default-user-password: "Vz123456789."

sync:
  cron: "0 0 2 * * ?"

logging:
  config: classpath:logback-spring.xml